FROM apache/airflow:2.6.0

USER root
RUN apt-get update && apt-get install -y gcc

USER airflow
RUN pip install --no-cache-dir \
    kagglehub \
    pillow \
    matplotlib \
    numpy \
    pandas \
    seaborn \
    sweetviz \
    gspread \
    oauth2client \
    scikit-learn \
    teapot \
    seaborn \
    torch \
    torchvision \
    tensorflow \
    pytest

COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt