version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.6.0
  environment:
    &airflow-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__DEFAULT_TIMEZONE: "UTC"
    AIRFLOW_UID: "50000"
    AIRFLOW_GID: "50000"
    _AIRFLOW_WWW_USER_USERNAME: admin
    _AIRFLOW_WWW_USER_PASSWORD: admin
  volumes:
    - ./src/airflow/dags:/opt/airflow/dags
    - ./src:/opt/airflow/scripts
    - airflow_logs:/opt/airflow/logs
    - airflow_plugins:/opt/airflow/plugins
    - ./src/airflow/credentials:/opt/airflow/credentials

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    depends_on:
      - postgres
    entrypoint: /bin/bash
    command:
      - -c
      - |
        echo "Initializing Airflow DB..."
        airflow db init
        echo "Creating admin user..."
        airflow users create \
          --username admin \
          --password admin \
          --firstname local \
          --lastname dev \
          --role Admin \
          --email admin@example.com
        echo "Airflow DB initialized and user created."

  airflow-webserver:
    build:
        context: ./src/airflow
        dockerfile: Dockerfile
    <<: *airflow-common
    container_name: airflow-webserver
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db upgrade &&
               airflow webserver"

  airflow-scheduler:
    build:
      context: ./src/airflow
      dockerfile: Dockerfile
    <<: *airflow-common
    container_name: airflow-scheduler
    depends_on:
      - airflow-init
    command: >
      bash -c "airflow db upgrade &&
               airflow scheduler"
    shm_size: '2g'

volumes:
  airflow_logs:
  airflow_plugins:
  postgres_data: