name: ML pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare data
        run: |
          python src/01_data_prep.py

      - name: Run EDA
        run: |
          python src/EDA.py

      - name: Normalize metadata.csv
        run: |
          python src/normalize_metadata.py
      
      # - name: Test train model
      #   run: |
      #     python src/autoML_testing.py

      - name: Prepare training data for CNN
        run: |
          python src/CNN/cnn_prep.py
